### ISSUE TITLE
self hosting 

### ISSUE THREAD

**Issue by matiasstornini** [benborgers/opensheet#20]
I have a doubt, I want to have everything installed in my own cloudflare, but the guide is very incomplete.
I have my own domain and everything, in cloudflare I have already cloned this repository, now, what do I have to do to make it finally work?

**Comment by benborgers** [comment]
Hi! If you have the repository cloned down, you can then use the Cloudflare Workers CLI (Wrangler) to deploy to Cloudflare Workers: https://developers.cloudflare.com/workers/get-started/guide

The only non-standard part of deploying it to Cloudflare Workers is that, after you’ve deployed it once, you should follow the directions in the readme in order to add your own Google Cloud API key for accessing the Google Sheets API. 

Let me know if you run into any trouble! I’m happy to help.

**Comment by matiasstornini** [comment]
Sorry, I tried but I couldn't make it work, I don't understand. If I use your opensheet service, how much traffic would it support per day, I estimate an average traffic of 250k per day

**Comment by benborgers** [comment]
@adiccfut It’s hosted on Cloudflare Workers which scales automatically, so it should be okay to handle any traffic that you throw at it (although I do pay the bill on that, but that’s okay). 

If it does become too much (for my wallet) I can ping you and help you set up your own instance of opensheet, but you should be good for now.
