### ISSUE TITLE
Intermittent downtime today?

### ISSUE THREAD

**Issue by dimavolo** [benborgers/opensheet#22]
Thanks for hosting opensheet! It has been working perfectly for months, but I noticed there may have been some random downtime today? Any indicators of this on your end?

**Comment by benborgers** [comment]
Sorry to hear that! My automatic monitors haven’t gone off, but do you have an example of an endpoint that you’re seeing downtime on? What kind of errors are you seeing?

**Comment by dimavolo** [comment]
Oh my, on further digging I'm getting:

> Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute' of service 'sheets.googleapis.com' for consumer 'project_number:###'

I had thought this caches requests and I didn't see mention of the quota in the docs. Previously I hadn't exceeded quota but I will try to limit my requests.

Please let me know the quota so that I can avoid coming close to it.

**Comment by benborgers** [comment]
Ah! The traffic runs through my Google Developers account, and the collective usage of Opensheet (across all users) has exceeded my account’s limits since the last time they were raised. I’ve requested a raised limit and that should resolve the issues you’re seeing. 

Sorry for the intermittent failures! Hopefully it’ll get addressed quite soon.

**Comment by dimavolo** [comment]
Nice catch. That became my suspicion as well. Thanks for taking care of this so quickly!

**Comment by benborgers** [comment]
Our quota has been roughly doubled so we should be good to go again. Thanks for bearing with me!
