### ISSUE TITLE
Unexpected results when merged cells in first row

### ISSUE THREAD

**Issue by dalin-** [benborgers/opensheet#6]
This project looks really promising!

In an example like this
<img width="1423" alt="Screen Shot 2022-01-04 at 9 21 25 PM" src="https://user-images.githubusercontent.com/1127349/148150634-c9c2ab08-4853-4d11-bac4-c06dc8dcf86c.png">
https://docs.google.com/spreadsheets/d/1-sU2EAuAO-C0TJQewpMSOWIFu4kIw2S_J961g2kDJKk/edit?alt=json&pli=1#gid=1290804713 

OpenSheet is only showing data from the last column of a merged header
https://opensheet.elk.sh/1-sU2EAuAO-C0TJQewpMSOWIFu4kIw2S_J961g2kDJKk/Vertical+Data

**Comment by benborgers** [comment]
Thank you! 

opensheet is hard-coded to take only the first row as a header, since that’s I think overwhelmingly the common use-case. This setup is really cool though! One thing you could do is to create your own spreadsheet that normalizes the data to have single-row headers. I went ahead and started it to show how it could work: https://docs.google.com/spreadsheets/d/1KujvRFev3sM0KaChU91IYRM04xIxa_dzXwf0TKU1-rg/edit#gid=0. It uses `=IMPORTRANGE` to pull live data out of that spreadsheet. Would that work? 

The other solution would be maybe to fork opensheet and create a version that specifically works with this spreadsheet, figuring out what the header should be based on the first `n` (in this case 5) rows.

**Comment by dalin-** [comment]
Thanks for the ideas Ben.  This project is just in the research phase, so it's a ways away from writing code. 

Another idea would be to invert the header rows, so the merged cells are in lines 2–5.
