### ISSUE TITLE
Awesome project!

### ISSUE THREAD

**Issue by tscanlin** [benborgers/opensheet#7]
Thank you for create a really cool & useful project! :)

**Comment by tscanlin** [comment]
feel free to close this, I just wanted to share some positive feedback.

**Comment by scott-coates** [comment]
I agree!

P.S. why did you switch from Vercel to Railway?

**Comment by benborgers** [comment]
Thank you both! 

I ran into the limits of the free tier on Vercel, and I don’t really have a reason to upgrade my plan on Vercel, but I was already paying on Railway so I decided to move it there. It looks like it’ll be cheaper to host on Railway (~$6/month) than Vercel’s pro plan ($20/month). Also, I can control caching on Railway using Redis instead of relying on Vercel’s CDN cache, which is more reliable!

**Comment by tiagorangel2011** [comment]
I do agree, this is awesome!
Every service I found is paid or if it is not it's heavily rate-limited. And then I find this one that's free and works very well!!!
